# Generated by Django 3.1.2 on 2021-02-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210219_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upimagesu',
            options={'ordering': ('visit',)},
        ),
        migrations.AddField(
            model_name='upimagesu',
            name='visit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
